# Generated by Django 6.0.1 on 2026-01-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Pokedex')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Pokémon')),
                ('name_inverted', models.CharField(max_length=100, verbose_name='Nombre Invertido')),
                ('types', models.JSONField(default=list, verbose_name='Tipos')),
                ('height', models.IntegerField(verbose_name='Altura')),
                ('weight', models.IntegerField(verbose_name='Peso')),
            ],
        ),
    ]
